### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by tjoye20** [Toughfluff/prj-rev-bwfs-dasmoto#1]
### Criteria 1: HTML and CSS Linking  
* _Score Level:_ 4 - Exceeds Expectations
 
### Criteria 2: Implementation of Design Specification and Content
* _Score Level:_ 4 - Exceeds Expectations
 
### Criteria 3: HTML Elements and Content
* _Score Level:_ 4 - Exceeds Expectations
 
### Criteria 4: CSS Selectors and Syntax
* _Score Level:_ 4 - Exceeds Expectations
 
### Overall Score: 16/16
Hey Gabrielle! You did a great job on this. You seem to have a really good grasp of the basics of HTML and CSS, excited to see your skills continue to grow! Quick note, you forgot the closing tag [here](https://github.com/Toughfluff/prj-rev-bwfs-dasmoto/blob/master/DasmotoProject/index.html#L36). Other than that, great effort on this. Keep it up!

**Comment by Toughfluff** [comment]
Yaaay. Thanks for the feedback :) and oops for that closing tag!
